import React from 'react';

const CurrencyContext = React.createContext({
  passenger: ['1', '2', '3', '4', '5'],
  flights: {
    Delhi: [
      {
        from: 'Delhi',
        to: 'Mumbai',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Ahmedabad',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Mumbai',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Pune',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Kolkata',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Chennai',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
    ],
    Mumbai: [
      {
        from: 'Delhi',
        to: 'Mumbai',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Ahmedabad',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Mumbai',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Pune',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Kolkata',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Chennai',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
    ],
    Bangalore: [
      {
        from: 'Delhi',
        to: 'Mumbai',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Ahmedabad',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Mumbai',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Pune',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Kolkata',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Chennai',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
    ],
    Chennai: [
      {
        from: 'Delhi',
        to: 'Mumbai',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Ahmedabad',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Mumbai',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Pune',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Kolkata',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Chennai',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
    ],
    Pune: [
      {
        from: 'Delhi',
        to: 'Mumbai',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Ahmedabad',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Mumbai',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Pune',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Kolkata',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Chennai',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
    ],
    Jaipur: [
      {
        from: 'Delhi',
        to: 'Mumbai',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Ahmedabad',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Mumbai',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Pune',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Kolkata',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
      {
        from: 'Delhi',
        to: 'Chennai',
        price: 3000,
        departure: '2:00AM',
        arrival: '3:00AM',
      },
    ],
  },
});

export default CurrencyContext;
